[versions]
coil = "2.5.0"
compileSdk = "35"
minSdk = "29"
buildTools = "35.0.0"
moshi = "1.15.2"
okhttp = "4.12.0"
retrofit = "2.9.0"
targetSdk = "35"
agp = "8.11.1"
kotlin = "2.2.10"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.2"
ksp-version = "2.2.10-2.0.2"
activityCompose = "1.10.1"
mockk-version = "1.13.11"
composeBom = "2025.07.00"
appcompat = "1.7.1"
material = "1.12.0"
hilt-version = "2.57"
room-version = "2.8.0"
hiltCompose-version = "1.2.0"
hilt-compose-navigation-version = "1.2.0"
navigation-compose-version = "2.9.2"
hilt-plugin-version = "2.57"
dagger-version = "2.57"
jetbrainsKotlinJvm = "2.2.10"
uiTooling = "1.9.4"
runtimeKtx = "2.10.2"
serialization-json = "1.9.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
jetbrains-kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization-json" }
runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "runtimeKtx" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-version" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt-version" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger-version" }
mockk-core = { group = "io.mockk", name = "mockk", version.ref = "mockk-version" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk-version" }
daggerKsp = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger-version" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
hiltNavigation = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltCompose-version" }
hiltKsp = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompose-version" }
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose-version" }
hilt-compose-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-compose-navigation-version" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room-version" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-version" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room-version" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }
serialization-json = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-plugin-version" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

